[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Serial Monitor settings
monitor_speed = 9600
monitor_filters = 
    colorize
    time
    send_on_enter
    

; Automatically detect the serial port
upload_port = auto
monitor_port = auto
monitor_echo = true
; Additional settings
build_flags = -D ARDUINO_AVR_UNO
lib_deps = 
    ; Add any libraries your project depends on here

; Custom upload command (uncomment if needed)
; upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i

; Ensure correct bootloader (uncomment if needed)
; board_bootloader = optiboot